### PR TITLE
Update to 3.7.2

### PR DESCRIPTION
**Pull request by androidacy-user**
Quick update to 3.7.2

### CODE REVIEW

**Comment by csagan5** [comment]
@alexa-v2 if you can remove the curl binaries then this should be fine.

Can you please also add the entry to the `CHANGELOG.md` file I created instead of README.md? I am doing that to keep it consistent with other projects, you might not like it though.

**Comment by androidacy-user** [comment]
@csagan5 binaries will be removed when I can either build at runtime or upload builds to report

And no problem with CHANGELOG.md lol just didn't think of that yet

**Comment by csagan5** [comment]
@alexa-v2 I meant from this PR, not from your repository.

I will pick the changes manually.

**Comment by androidacy-user** [comment]
*repo not report

**Pull request closed without merging**
