### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by androidacy-user**
Since this is going official, the language separating me from the project is unnecessary

### CODE REVIEW

**Comment by csagan5** [comment]
See https://github.com/Magisk-Modules-Repo/bromitewebview/issues/1

**Comment by androidacy-user** [comment]
I'm going to open an issue on magisk modules repo

**Comment by androidacy-user** [comment]
See here @csagan5 https://github.com/Magisk-Modules-Repo/submission/issues/465

**Comment by csagan5** [comment]
As per discussion in #4 I am closing this; let's discuss the topic further there.

**Pull request closed without merging**
